export default function HospitalUploadGuidePage() {
  return (
    <div className="space-y-8">
      <div className="border-b border-gray-200 pb-6">
        <p className="text-sm uppercase tracking-wide text-primary">Runbook</p>
        <h1 className="mt-2 text-4xl font-bold text-gray-900">Hospital Upload Playbook</h1>
        <p className="mt-4 text-lg text-gray-600">
          Step-by-step checklist for running the hospital CSV upload in production or for demo
          recordings. Follow this guide to avoid adapter failures and frontend timeouts.
        </p>
      </div>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-gray-900">1. CSV Requirements</h2>
        <p className="text-gray-700">
          The adapter enforces k-anonymity and requires demographic fields in every row. Use this
          exact header row (case-sensitive):
        </p>
        <pre className="overflow-auto rounded-lg bg-gray-900 p-4 text-sm text-green-200">
{`Patient ID,Patient Name,Age,Gender,Date of Birth,Address,Country,Lab Test,Result,Test Date,Condition,ICD10 Code`}
        </pre>
        <p className="text-gray-700">
          Every record must contain <strong>Patient Name</strong> plus either{' '}
          <strong>Age</strong> or <strong>Date of Birth</strong>. The adapter cannot calculate the
          age range or generate a UPI without those fields and will abort with a 500 error.
        </p>
        <div className="rounded-lg border border-gray-200 bg-white p-4">
          <p className="text-sm font-semibold text-gray-900">Sample row</p>
          <pre className="mt-2 overflow-auto rounded bg-gray-50 p-3 text-sm text-gray-800">
{`PAT-201,Grace Namatovu,42,Female,1983-09-14,"45 Makerere Hill Rd, Kampala",Uganda,HbA1c,6.8,2024-02-10,Diabetes Type 2,E11.9`}
          </pre>
        </div>
        <p className="text-gray-700">
          Tip: reuse the test CSV generated by <code>scripts/test-complete-data-flow.sh</code> for a
          known-good template (5 rows, all required columns).
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-gray-900">2. Upload Flow</h2>
        <ol className="list-decimal space-y-3 pl-6 text-gray-700">
          <li>
            Register or log into the hospital portal at <code>/hospital/login</code> using the
            hospital ID and API key from the backend response.
          </li>
          <li>
            Open <code>/hospital/upload</code>, select your CSV, and click{' '}
            <strong>Upload and Process</strong>.
          </li>
          <li>
            Monitor the toast + processing card. On success you should see records processed,
            consent/data proof counts, and topic IDs.
          </li>
          <li>
            (Optional) Open <code>/hospital/processing</code> or the HashScan links to show the
            immutable Hedera proof in the demo.
          </li>
        </ol>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-gray-900">3. Handling 504 Timeouts</h2>
        <p className="text-gray-700">
          Creating Hedera accounts for large CSVs can exceed Vercel&apos;s ~10s API timeout. The
          backend keeps working, but the browser may show a 504.
        </p>
        <ul className="list-disc space-y-2 pl-6 text-gray-700">
          <li>
            For demo recordings, limit the CSV to 5–10 rows so processing finishes before the
            timeout.
          </li>
          <li>
            If you must process a larger file, let the upload run even if the UI times out—data will
            appear in processing history once the adapter completes.
          </li>
          <li>
            Mention during the demo that long-running jobs continue in the background and refresh
            the dashboard to show the completed run.
          </li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-gray-900">4. Troubleshooting</h2>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          <div className="rounded-lg border border-red-200 bg-red-50 p-4">
            <p className="font-semibold text-red-700">500 – “Age is required”</p>
            <p className="text-sm text-red-600">
              At least one row is missing <strong>Age</strong> and <strong>Date of Birth</strong>.
              Fix the CSV and re-upload.
            </p>
          </div>
          <div className="rounded-lg border border-yellow-200 bg-yellow-50 p-4">
            <p className="font-semibold text-yellow-800">504 – Timeout</p>
            <p className="text-sm text-yellow-700">
              The adapter is still running. Either wait for the backend to finish or use a smaller
              CSV for the demo.
            </p>
          </div>
          <div className="rounded-lg border border-blue-200 bg-blue-50 p-4">
            <p className="font-semibold text-blue-800">HashScan not showing data</p>
            <p className="text-sm text-blue-700">
              Transactions can take a few seconds to index. Keep a previous run&apos;s link handy as
              a backup screenshot.
            </p>
          </div>
          <div className="rounded-lg border border-green-200 bg-green-50 p-4">
            <p className="font-semibold text-green-800">Need a template fast?</p>
            <p className="text-sm text-green-700">
              Run <code>./scripts/test-complete-data-flow.sh</code> locally to generate a CSV in{' '}
              <code>/tmp</code> that already matches the schema.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}

